In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/gapminder.tsv', sep='\t')

In [3]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [4]:
df.country.value_counts()

France          12
Paraguay        12
South Africa    12
Portugal        12
Jamaica         12
                ..
Egypt           12
Slovenia        12
Bulgaria        12
Saudi Arabia    12
Philippines     12
Name: country, Length: 142, dtype: int64

In [5]:
cts = df.country.value_counts()

In [6]:
type(cts)

pandas.core.series.Series

In [7]:
cts.index.str.contains('Costa').any()

True

In [8]:
df[df.country == 'Costa Rica']

        country continent  year  lifeExp      pop    gdpPercap
348  Costa Rica  Americas  1952   57.206   926317  2627.009471
349  Costa Rica  Americas  1957   60.026  1112300  2990.010802
350  Costa Rica  Americas  1962   62.842  1345187  3460.937025
351  Costa Rica  Americas  1967   65.424  1588717  4161.727834
352  Costa Rica  Americas  1972   67.849  1834796  5118.146939
353  Costa Rica  Americas  1977   70.750  2108457  5926.876967
354  Costa Rica  Americas  1982   73.450  2424367  5262.734751
355  Costa Rica  Americas  1987   74.752  2799811  5629.915318
356  Costa Rica  Americas  1992   75.713  3173216  6160.416317
357  Costa Rica  Americas  1997   77.260  3518107  6677.045314
358  Costa Rica  Americas  2002   78.123  3834934  7723.447195
359  Costa Rica  Americas  2007   78.782  4133884  9645.061420

In [9]:
df[df.country == 'Costa Rica'].continent = 'South America'

c:\users\cw\appdata\local\programs\python\python36\lib\site-packages\pandas\core\generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [10]:
df[df.country == 'Costa Rica']

        country continent  year  lifeExp      pop    gdpPercap
348  Costa Rica  Americas  1952   57.206   926317  2627.009471
349  Costa Rica  Americas  1957   60.026  1112300  2990.010802
350  Costa Rica  Americas  1962   62.842  1345187  3460.937025
351  Costa Rica  Americas  1967   65.424  1588717  4161.727834
352  Costa Rica  Americas  1972   67.849  1834796  5118.146939
353  Costa Rica  Americas  1977   70.750  2108457  5926.876967
354  Costa Rica  Americas  1982   73.450  2424367  5262.734751
355  Costa Rica  Americas  1987   74.752  2799811  5629.915318
356  Costa Rica  Americas  1992   75.713  3173216  6160.416317
357  Costa Rica  Americas  1997   77.260  3518107  6677.045314
358  Costa Rica  Americas  2002   78.123  3834934  7723.447195
359  Costa Rica  Americas  2007   78.782  4133884  9645.061420

In [11]:
df.loc[df.country == 'Costa Rica', 'continent'] = "South America"

In [12]:
df[df.country == 'Costa Rica']

        country      continent  year  lifeExp      pop    gdpPercap
348  Costa Rica  South America  1952   57.206   926317  2627.009471
349  Costa Rica  South America  1957   60.026  1112300  2990.010802
350  Costa Rica  South America  1962   62.842  1345187  3460.937025
351  Costa Rica  South America  1967   65.424  1588717  4161.727834
352  Costa Rica  South America  1972   67.849  1834796  5118.146939
353  Costa Rica  South America  1977   70.750  2108457  5926.876967
354  Costa Rica  South America  1982   73.450  2424367  5262.734751
355  Costa Rica  South America  1987   74.752  2799811  5629.915318
356  Costa Rica  South America  1992   75.713  3173216  6160.416317
357  Costa Rica  South America  1997   77.260  3518107  6677.045314
358  Costa Rica  South America  2002   78.123  3834934  7723.447195
359  Costa Rica  South America  2007   78.782  4133884  9645.061420

In [13]:
cr = df.loc[df.country == 'Costa Rica']

In [14]:
cr

        country      continent  year  lifeExp      pop    gdpPercap
348  Costa Rica  South America  1952   57.206   926317  2627.009471
349  Costa Rica  South America  1957   60.026  1112300  2990.010802
350  Costa Rica  South America  1962   62.842  1345187  3460.937025
351  Costa Rica  South America  1967   65.424  1588717  4161.727834
352  Costa Rica  South America  1972   67.849  1834796  5118.146939
353  Costa Rica  South America  1977   70.750  2108457  5926.876967
354  Costa Rica  South America  1982   73.450  2424367  5262.734751
355  Costa Rica  South America  1987   74.752  2799811  5629.915318
356  Costa Rica  South America  1992   75.713  3173216  6160.416317
357  Costa Rica  South America  1997   77.260  3518107  6677.045314
358  Costa Rica  South America  2002   78.123  3834934  7723.447195
359  Costa Rica  South America  2007   78.782  4133884  9645.061420

In [15]:
cr['continent'] = "Americas"

c:\users\cw\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
cr

        country continent  year  lifeExp      pop    gdpPercap
348  Costa Rica  Americas  1952   57.206   926317  2627.009471
349  Costa Rica  Americas  1957   60.026  1112300  2990.010802
350  Costa Rica  Americas  1962   62.842  1345187  3460.937025
351  Costa Rica  Americas  1967   65.424  1588717  4161.727834
352  Costa Rica  Americas  1972   67.849  1834796  5118.146939
353  Costa Rica  Americas  1977   70.750  2108457  5926.876967
354  Costa Rica  Americas  1982   73.450  2424367  5262.734751
355  Costa Rica  Americas  1987   74.752  2799811  5629.915318
356  Costa Rica  Americas  1992   75.713  3173216  6160.416317
357  Costa Rica  Americas  1997   77.260  3518107  6677.045314
358  Costa Rica  Americas  2002   78.123  3834934  7723.447195
359  Costa Rica  Americas  2007   78.782  4133884  9645.061420

In [17]:
cr = df.loc[df.country == 'Costa Rica'].copy()

In [18]:
cr['continent'] = "Americas"

In [19]:
cr['continent']

348    Americas
349    Americas
350    Americas
351    Americas
352    Americas
353    Americas
354    Americas
355    Americas
356    Americas
357    Americas
358    Americas
359    Americas
Name: continent, dtype: object