In [1]:
import numpy as np

In [2]:
np.NaN

nan

In [3]:
from numpy import NaN, NAN, nan
# from numpy import *

In [4]:
NaN

nan

In [5]:
NaN == True

False

In [6]:
NaN == False

False

In [7]:
NaN == NaN

False

In [8]:
import pandas as pd

In [10]:
pd.isnull(None)

True

In [11]:
pd.isna(None)

True

In [12]:
pd.notnull(42)

True

In [18]:
not pd.isna(None)

False

In [20]:
pd.read_csv('../data/survey_visited.csv', keep_default_na=False)

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [21]:
pd.read_csv('../data/survey_visited.csv', na_values=[619, 622])

   ident   site       dated
0    NaN   DR-1  1927-02-08
1    NaN   DR-1  1927-02-10
2  734.0   DR-3  1939-01-07
3  735.0   DR-3  1930-01-12
4  751.0   DR-3  1930-02-26
5  752.0   DR-3         NaN
6  837.0  MSK-4  1932-01-14
7  844.0   DR-1  1932-03-22

In [22]:
ebola = pd.read_csv('../data/country_timeseries.csv')

In [23]:
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [24]:
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
Date                   122 non-null object
Day                    122 non-null int64
Cases_Guinea           93 non-null float64
Cases_Liberia          83 non-null float64
Cases_SierraLeone      87 non-null float64
Cases_Nigeria          38 non-null float64
Cases_Senegal          25 non-null float64
Cases_UnitedStates     18 non-null float64
Cases_Spain            16 non-null float64
Cases_Mali             12 non-null float64
Deaths_Guinea          92 non-null float64
Deaths_Liberia         81 non-null float64
Deaths_SierraLeone     87 non-null float64
Deaths_Nigeria         38 non-null float64
Deaths_Senegal         22 non-null float64
Deaths_UnitedStates    18 non-null float64
Deaths_Spain           16 non-null float64
Deaths_Mali            12 non-null float64
dtypes: float64(16), int64(1), object(1)
memory usage: 17.2+ KB

In [27]:
ebola.Cases_Guinea.value_counts(dropna=False).head()

NaN       29
 86.0      3
 495.0     2
 112.0     2
 390.0     2
Name: Cases_Guinea, dtype: int64

In [33]:
assert not pd.isnull(ebola.Cases_Guinea).any(), 'missing value found'

AssertionError: missing value found

In [34]:
ebola.fillna(0)

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,0.0,10030.0,0.0,0.0,0.0,0.0,0.0,1786.0,0.0,2977.0,0.0,0.0,0.0,0.0,0.0
1,1/4/2015,288,2775.0,0.0,9780.0,0.0,0.0,0.0,0.0,0.0,1781.0,0.0,2943.0,0.0,0.0,0.0,0.0,0.0
2,1/3/2015,287,2769.0,8166.0,9722.0,0.0,0.0,0.0,0.0,0.0,1767.0,3496.0,2915.0,0.0,0.0,0.0,0.0,0.0
3,1/2/2015,286,0.0,8157.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3496.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12/31/2014,284,2730.0,8115.0,9633.0,0.0,0.0,0.0,0.0,0.0,1739.0,3471.0,2827.0,0.0,0.0,0.0,0.0,0.0
5,12/28/2014,281,2706.0,8018.0,9446.0,0.0,0.0,0.0,0.0,0.0,1708.0,3423.0,2758.0,0.0,0.0,0.0,0.0,0.0
6,12/27/2014,280,2695.0,0.0,9409.0,0.0,0.0,0.0,0.0,0.0,1697.0,0.0,2732.0,0.0,0.0,0.0,0.0,0.0
7,12/24/2014,277,2630.0,7977.0,9203.0,0.0,0.0,0.0,0.0,0.0,0.0,3413.0,2655.0,0.0,0.0,0.0,0.0,0.0
8,12/21/2014,273,2597.0,0.0,9004.0,0.0,0.0,0.0,0.0,0.0,1607.0,0.0,2582.0,0.0,0.0,0.0,0.0,0.0
9,12/20/2014,272,2571.0,7862.0,8939.0,0.0,0.0,0.0,0.0,0.0,1586.0,3384.0,2556.0,0.0,0.0,0.0,0.0,0.0
10,12/18/2014,271,0.0,7830.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3376.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12/14/2014,267,2416.0,0.0,8356.0,0.0,0.0,0.0,0.0,0.0,1525.0,0.0,2085.0,0.0,0.0,0.0,0.0,0.0
12,12/9/2014,262,0.0,7797.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3290.0,0.0,0.0,0.0,0.0,0.0,0.0
13,12/7/2014,260,2292.0,0.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,0.0,1768.0,8.0,0.0,1.0,0.0,6.0
14,12/3/2014,256,0.0,7719.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3177.0,0.0,0.0,0.0,0.0,0.0,0.0
15,11/30/2014,253,2164.0,0.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,0.0,1583.0,8.0,0.0,1.0,0.0,6.0
16,11/28/2014,251,0.0,7635.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3145.0,0.0,0.0,0.0,0.0,0.0,0.0
17,11/23/2014,246,2134.0,0.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,0.0,1398.0,8.0,0.0,1.0,0.0,6.0
18,11/22/2014,245,0.0,7168.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3016.0,0.0,0.0,0.0,0.0,0.0,0.0
19,11/18/2014,241,2047.0,7082.0,6190.0,20.0,1.0,4.0,1.0,6.0,1214.0,2963.0,1267.0,8.0,0.0,1.0,0.0,6.0
20,11/16/2014,239,1971.0,0.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,0.0,1250.0,8.0,0.0,1.0,0.0,5.0
21,11/15/2014,238,0.0,7069.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2964.0,0.0,0.0,0.0,0.0,0.0,0.0
22,11/11/2014,234,1919.0,0.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,0.0,1187.0,8.0,0.0,1.0,0.0,3.0
23,11/10/2014,233,0.0,6878.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2812.0,0.0,0.0,0.0,0.0,0.0,0.0
24,11/9/2014,232,1878.0,0.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,0.0,1169.0,8.0,0.0,1.0,0.0,1.0
25,11/8/2014,231,0.0,6822.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2836.0,0.0,0.0,0.0,0.0,0.0,0.0
26,11/4/2014,227,0.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,0.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
27,11/3/2014,226,1760.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1054.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,11/2/2014,225,1731.0,0.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,0.0,1070.0,8.0,0.0,1.0,0.0,1.0
29,10/31/2014,222,0.0,6525.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2697.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,5/23/2014,62,258.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,174.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
93,5/12/2014,51,248.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,171.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
94,5/10/2014,49,233.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,157.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
95,5/7/2014,46,236.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,158.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
96,5/5/2014,44,235.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,157.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
97,5/3/2014,42,231.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,155.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
98,5/1/2014,40,226.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,149.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
99,4/26/2014,35,224.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,143.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,4/24/2014,33,0.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,4/23/2014,32,218.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,141.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,4/22/2014,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,4/21/2014,30,0.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
104,4/20/2014,29,208.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,136.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
105,4/17/2014,26,203.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,129.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
106,4/16/2014,25,197.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,122.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0
107,4/15/2014,24,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
108,4/14/2014,23,168.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,108.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,4/11/2014,20,159.0,26.0,2.0,0.0,0.0,0.0,0.0,0.0,106.0,13.0,2.0,0.0,0.0,0.0,0.0,0.0
110,4/9/2014,18,158.0,25.0,2.0,0.0,0.0,0.0,0.0,0.0,101.0,12.0,2.0,0.0,0.0,0.0,0.0,0.0
111,4/7/2014,16,151.0,21.0,2.0,0.0,0.0,0.0,0.0,0.0,95.0,10.0,2.0,0.0,0.0,0.0,0.0,0.0
112,4/4/2014,13,143.0,18.0,2.0,0.0,0.0,0.0,0.0,0.0,86.0,7.0,2.0,0.0,0.0,0.0,0.0,0.0
113,4/1/2014,10,127.0,8.0,2.0,0.0,0.0,0.0,0.0,0.0,83.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0
114,3/31/2014,9,122.0,8.0,2.0,0.0,0.0,0.0,0.0,0.0,80.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0
115,3/29/2014,7,112.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
116,3/28/2014,6,112.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,70.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0
117,3/27/2014,5,103.0,8.0,6.0,0.0,0.0,0.0,0.0,0.0,66.0,6.0,5.0,0.0,0.0,0.0,0.0,0.0
118,3/26/2014,4,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,3/25/2014,3,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
120,3/24/2014,2,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,3/22/2014,0,49.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
ebola.fillna(method='ffill')

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2769.0,8157.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
5,12/28/2014,281,2706.0,8018.0,9446.0,NaN,NaN,NaN,NaN,NaN,1708.0,3423.0,2758.0,NaN,NaN,NaN,NaN,NaN
6,12/27/2014,280,2695.0,8018.0,9409.0,NaN,NaN,NaN,NaN,NaN,1697.0,3423.0,2732.0,NaN,NaN,NaN,NaN,NaN
7,12/24/2014,277,2630.0,7977.0,9203.0,NaN,NaN,NaN,NaN,NaN,1697.0,3413.0,2655.0,NaN,NaN,NaN,NaN,NaN
8,12/21/2014,273,2597.0,7977.0,9004.0,NaN,NaN,NaN,NaN,NaN,1607.0,3413.0,2582.0,NaN,NaN,NaN,NaN,NaN
9,12/20/2014,272,2571.0,7862.0,8939.0,NaN,NaN,NaN,NaN,NaN,1586.0,3384.0,2556.0,NaN,NaN,NaN,NaN,NaN
10,12/18/2014,271,2571.0,7830.0,8939.0,NaN,NaN,NaN,NaN,NaN,1586.0,3376.0,2556.0,NaN,NaN,NaN,NaN,NaN
11,12/14/2014,267,2416.0,7830.0,8356.0,NaN,NaN,NaN,NaN,NaN,1525.0,3376.0,2085.0,NaN,NaN,NaN,NaN,NaN
12,12/9/2014,262,2416.0,7797.0,8356.0,NaN,NaN,NaN,NaN,NaN,1525.0,3290.0,2085.0,NaN,NaN,NaN,NaN,NaN
13,12/7/2014,260,2292.0,7797.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3290.0,1768.0,8.0,0.0,1.0,0.0,6.0
14,12/3/2014,256,2292.0,7719.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3177.0,1768.0,8.0,0.0,1.0,0.0,6.0
15,11/30/2014,253,2164.0,7719.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3177.0,1583.0,8.0,0.0,1.0,0.0,6.0
16,11/28/2014,251,2164.0,7635.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3145.0,1583.0,8.0,0.0,1.0,0.0,6.0
17,11/23/2014,246,2134.0,7635.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3145.0,1398.0,8.0,0.0,1.0,0.0,6.0
18,11/22/2014,245,2134.0,7168.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3016.0,1398.0,8.0,0.0,1.0,0.0,6.0
19,11/18/2014,241,2047.0,7082.0,6190.0,20.0,1.0,4.0,1.0,6.0,1214.0,2963.0,1267.0,8.0,0.0,1.0,0.0,6.0
20,11/16/2014,239,1971.0,7082.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,2963.0,1250.0,8.0,0.0,1.0,0.0,5.0
21,11/15/2014,238,1971.0,7069.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,2964.0,1250.0,8.0,0.0,1.0,0.0,5.0
22,11/11/2014,234,1919.0,7069.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2964.0,1187.0,8.0,0.0,1.0,0.0,3.0
23,11/10/2014,233,1919.0,6878.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2812.0,1187.0,8.0,0.0,1.0,0.0,3.0
24,11/9/2014,232,1878.0,6878.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2812.0,1169.0,8.0,0.0,1.0,0.0,1.0
25,11/8/2014,231,1878.0,6822.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2836.0,1169.0,8.0,0.0,1.0,0.0,1.0
26,11/4/2014,227,1878.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,1142.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
27,11/3/2014,226,1760.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,1054.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
28,11/2/2014,225,1731.0,6619.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,2766.0,1070.0,8.0,0.0,1.0,0.0,1.0
29,10/31/2014,222,1731.0,6525.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,2697.0,1070.0,8.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,5/23/2014,62,258.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,174.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
93,5/12/2014,51,248.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,171.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
94,5/10/2014,49,233.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,157.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
95,5/7/2014,46,236.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,158.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
96,5/5/2014,44,235.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,157.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
97,5/3/2014,42,231.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,155.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
98,5/1/2014,40,226.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,149.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
99,4/26/2014,35,224.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,143.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
100,4/24/2014,33,224.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,143.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
101,4/23/2014,32,218.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
102,4/22/2014,31,218.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
103,4/21/2014,30,218.0,34.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
104,4/20/2014,29,208.0,34.0,0.0,0.0,1.0,1.0,1.0,1.0,136.0,6.0,0.0,0.0,0.0,0.0,1.0,1.0
105,4/17/2014,26,203.0,27.0,0.0,0.0,1.0,1.0,1.0,1.0,129.0,6.0,0.0,0.0,0.0,0.0,1.0,1.0
106,4/16/2014,25,197.0,27.0,0.0,0.0,1.0,1.0,1.0,1.0,122.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
107,4/15/2014,24,197.0,27.0,12.0,0.0,1.0,1.0,1.0,1.0,122.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
108,4/14/2014,23,168.0,27.0,12.0,0.0,1.0,1.0,1.0,1.0,108.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
109,4/11/2014,20,159.0,26.0,2.0,0.0,1.0,1.0,1.0,1.0,106.0,13.0,2.0,0.0,0.0,0.0,1.0,1.0
110,4/9/2014,18,158.0,25.0,2.0,0.0,1.0,1.0,1.0,1.0,101.0,12.0,2.0,0.0,0.0,0.0,1.0,1.0
111,4/7/2014,16,151.0,21.0,2.0,0.0,1.0,1.0,1.0,1.0,95.0,10.0,2.0,0.0,0.0,0.0,1.0,1.0
112,4/4/2014,13,143.0,18.0,2.0,0.0,1.0,1.0,1.0,1.0,86.0,7.0,2.0,0.0,0.0,0.0,1.0,1.0
113,4/1/2014,10,127.0,8.0,2.0,0.0,1.0,1.0,1.0,1.0,83.0,5.0,2.0,0.0,0.0,0.0,1.0,1.0
114,3/31/2014,9,122.0,8.0,2.0,0.0,1.0,1.0,1.0,1.0,80.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0
115,3/29/2014,7,112.0,7.0,2.0,0.0,1.0,1.0,1.0,1.0,70.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0
116,3/28/2014,6,112.0,3.0,2.0,0.0,1.0,1.0,1.0,1.0,70.0,3.0,2.0,0.0,0.0,0.0,1.0,1.0
117,3/27/2014,5,103.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,66.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
118,3/26/2014,4,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,62.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
119,3/25/2014,3,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,60.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
120,3/24/2014,2,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,59.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
121,3/22/2014,0,49.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,29.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0

In [38]:
ebola.interpolate?

Signature: ebola.interpolate(method='linear', axis=0, limit=None, inplace=False, limit_direction='forward', limit_area=None, downcast=None, **kwargs)
Docstring:
Interpolate values according to different methods.

Please note that only ``method='linear'`` is supported for
DataFrames/Series with a MultiIndex.

Parameters
----------
method : {'linear', 'time', 'index', 'values', 'nearest', 'zero',
          'slinear', 'quadratic', 'cubic', 'barycentric', 'krogh',
          'polynomial', 'spline', 'piecewise_polynomial',
          'from_derivatives', 'pchip', 'akima'}

    * 'linear': ignore the index and treat the values as equally
      spaced. This is the only method supported on MultiIndexes.
      default
    * 'time': interpolation works on daily and higher resolution
      data to interpolate given length of interval
    * 'index', 'values': use the actual numerical values of the index
    * 'nearest', 'zero', 'slinear', 'quadratic', 'cubic',
      'barycentric', 'polynomial' is passed to
      ``scipy.interpolate.interp1d``. Both 'polynomial' and 'spline'
      require that you also specify an `order` (int),
      e.g. df.interpolate(method='polynomial', order=4).
      These use the actual numerical values of the index.
    * 'krogh', 'piecewise_polynomial', 'spline', 'pchip' and 'akima'
      are all wrappers around the scipy interpolation methods of
      similar names. These use the actual numerical values of the
      index. For more information on their behavior, see the
      `scipy documentation
      <http://docs.scipy.org/doc/scipy/reference/interpolate.html#univariate-interpolation>`__
      and `tutorial documentation
      <http://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html>`__
    * 'from_derivatives' refers to BPoly.from_derivatives which
      replaces 'piecewise_polynomial' interpolation method in
      scipy 0.18

    .. versionadded:: 0.18.1

       Added support for the 'akima' method
       Added interpolate method 'from_derivatives' which replaces
       'piecewise_polynomial' in scipy 0.18; backwards-compatible with
       scipy < 0.18

axis : {0, 1}, default 0
    * 0: fill column-by-column
    * 1: fill row-by-row
limit : int, default None.
    Maximum number of consecutive NaNs to fill. Must be greater than 0.
limit_direction : {'forward', 'backward', 'both'}, default 'forward'
limit_area : {'inside', 'outside'}, default None
    * None: (default) no fill restriction
    * 'inside' Only fill NaNs surrounded by valid values (interpolate).
    * 'outside' Only fill NaNs outside valid values (extrapolate).

    If limit is specified, consecutive NaNs will be filled in this
    direction.

    .. versionadded:: 0.21.0
inplace : bool, default False
    Update the NDFrame in place if possible.
downcast : optional, 'infer' or None, defaults to None
    Downcast dtypes if possible.
kwargs : keyword arguments to pass on to the interpolating function.

Returns
-------
Series or DataFrame of same shape interpolated at the NaNs

See Also
--------
reindex, replace, fillna

Examples
--------

Filling in NaNs

>>> s = pd.Series([0, 1, np.nan, 3])
>>> s.interpolate()
0    0
1    1
2    2
3    3
dtype: float64
File:      c:\users\danie\anaconda3\lib\site-packages\pandas\core\generic.py
Type:      method